#!/usr/bin/env bash

COLUMNS=10

echo "Ansible Playbook Runner"
echo ""

OPTIONS=(
  "Initialise  - Ansible Galaxy Install"
  "Install     - Google Cloud SDK locally"
  "Initialise  - Google Cloud Login"
  "Install     - Create Anthos Workstation"
  "Install     - Create Anthos Cluster"
  "Configure   - Anthos for Cloud Console"
  "Install     - Anthos Service Mesh"
)

PS3='Select an operation: '
select OPT in "${OPTIONS[@]}"
do
  case $OPT in

    "Initialise  - Ansible Galaxy Install")
      pip3 install requests google-auth
      ansible-galaxy collection install -r vars/galaxy-requirements.yml
      ;;

    "Install     - Google Cloud SDK locally")
      ansible-playbook install-google-cloud-sdk.yml
      ;;

    "Initialise  - Google Cloud Login")
      gcloud auth login --update-adc
      echo "Enter your Anthos project ID"
      read projectid
      gcloud config set project $projectid
      gcloud config list
      ;;

    "Install     - Create Anthos Workstation")
      ansible-playbook create-anthos-workstation.yml
      ;;

    "Install     - Create Anthos Cluster")
      ansible-playbook create-anthos-cluster.yml
      ;;
    
    "Configure   - Anthos for Cloud Console")
      ansible-playbook configure-anthos.yml
      ;;

    "Install     - Anthos Service Mesh")
      ansible-playbook install-asm.yml
      ;;
    *)
      echo "Invalid option '${OPT}'"
      ;;

  esac
  break
done
