anthos_workstation:
  hosts:
    anthos-workstation:
      ansible_host: 192.168.1.13
  vars:
    ansible_python_interpreter: /usr/bin/python3
      
anthos_cluster:
  hosts:
    box2:
      ansible_host: 10.1.1.11
    box3:
      ansible_host: 10.1.1.12
  vars:
    ansible_ssh_extra_args: "-J {{ ansible_service_account }}@{{ box1_public_address }}"
    ansible_scp_extra_args: "-o \"ProxyJump {{ ansible_service_account }}@{{ box1_public_address }}\""
    ansible_python_interpreter: /usr/bin/python3
