anthos_workstation:
  hosts:
    anthos-workstation:
      ansible_host: 192.168.1.13
  vars:
    ansible_python_interpreter: /usr/bin/python3
      
anthos_cluster:
  hosts:
    snuc1:
      ansible_host: 10.1.1.11
    snuc2:
      ansible_host: 10.1.1.12
  vars:
    ansible_ssh_extra_args: "-J snuc@192.168.1.13"
    ansible_scp_extra_args: "-o \"ProxyJump snuc@192.168.1.13\""
    ansible_python_interpreter: /usr/bin/python3
