# Copyright 2021, Matthew Winter
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


---

- name: Create the "login_user" for OS Family
  ansible.builtin.include_tasks:
    file: 'setup-login-user-{{ ansible_os_family | lower }}.yml'
    apply:
      become: true

- name: Configure the "login_user" for Passwordless "sudo"
  ansible.builtin.template:
    src: sudoers.j2
    dest: '/etc/sudoers.d/00-{{ login_user }}'
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true

- name: Create "authorized_keys" for the "login_user"
  ansible.builtin.shell:
    cmd: |
      set -o pipefail
      cp {{ ansible_user_dir }}/.ssh/authorized_keys {{ ansible_user_dir }}/../{{ login_user }}/.ssh/authorized_keys
      chown {{ login_user }}: {{ ansible_user_dir }}/../{{ login_user }}/.ssh/authorized_keys
      chmod 600 {{ ansible_user_dir }}/../{{ login_user }}/.ssh/authorized_keys
  args:
    executable: /bin/bash
  become: true
  changed_when: false
