# Copyright 2021, Matthew Winter
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


---

- name: Create the "login_user" account [Debian / Ubuntu]
  ansible.builtin.user:
    name: "{{ login_user }}"
    comment: "Anthos Login User"
    shell: /bin/bash
    groups: sudo
    append: yes
    generate_ssh_key: yes
    ssh_key_file: ".ssh/id_rsa"
    ssh_key_comment: "{{ login_user }}@{{ ansible_hostname }}"
