kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-console-reader-binding
  namespace: default
subjects:
- kind: User
  name: {{ KSA_NAME }}
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: cloud-console-reader
  apiGroup: rbac.authorization.k8s.io