kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloud-console-reader-binding
subjects:
- kind: ServiceAccount
  name: {{ KSA_NAME }}
  namespace: default
roleRef:
  kind: ClusterRole
  name: cloud-console-reader
  apiGroup: rbac.authorization.k8s.io